# Generated by Django 4.2.30 on 2026-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0002_uploadedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='staus',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('preprocessed', 'Preprocessed'), ('segmented', 'Segmented'), ('ocr_done', 'OCR Complete')], default='uploaded', max_length=20),
        ),
    ]
