# Generated by Django 4.2.30 on 2026-06-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0003_uploadedimage_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='staus',
            new_name='status',
        ),
    ]
