# Generated by Django 4.2.30 on 2026-06-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0004_rename_staus_uploadedimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='original_backup',
            field=models.ImageField(blank=True, null=True, upload_to='backups/'),
        ),
    ]
