# Generated by Django 4.2.30 on 2026-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0005_uploadedimage_original_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
