# Generated by Django 4.2.30 on 2026-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0006_uploadedimage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='locked_image',
            field=models.ImageField(blank=True, null=True, upload_to='locked/'),
        ),
    ]
