# Generated by Django 4.2.30 on 2026-06-23 11:23

from django.db import migrations, models
import htr.models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0007_uploadedimage_locked_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='original_image',
            field=models.ImageField(upload_to=htr.models.user_upload_path),
        ),
    ]
