# Generated by Django 4.2.30 on 2026-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0008_alter_uploadedimage_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='preprocessing_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
