# Generated by Django 4.2.30 on 2026-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0009_uploadedimage_preprocessing_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='line_coordinates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
