# Generated by Django 4.2.30 on 2026-06-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0010_uploadedimage_line_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='line_coordinates',
        ),
    ]
