# Generated by Django 4.2.30 on 2026-06-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0011_remove_uploadedimage_line_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='page_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='page_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
