# Generated by Django 4.2.30 on 2026-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0012_uploadedimage_page_height_uploadedimage_page_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='page_height',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='page_width',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='line_coordinates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
