# Generated by Django 4.2.30 on 2026-06-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0014_uploadedimage_ocr_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='ocr_stale',
            field=models.BooleanField(default=False),
        ),
    ]
