# Generated by Django 4.2.30 on 2026-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0015_uploadedimage_ocr_stale'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='last_save_seq',
            field=models.IntegerField(default=0),
        ),
    ]
