# Generated by Django 4.2.30 on 2026-06-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0016_uploadedimage_last_save_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='last_save_seq',
        ),
    ]
