# Generated by Django 4.2.30 on 2026-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htr', '0017_remove_uploadedimage_last_save_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='line_padding',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
